name: first wokflow
env:
  WORKFLOW_VAR: "This variable ist declaraed"
  


on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello Worls! This is the rist job
      - name: checkout
        uses: actions/checkout@v3
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Peter from here"
      - name: time
        run: |
          echo: "The time of greeting: ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second
          echo and this is the multi-line script
